import eslint from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.strict,
  ...tseslint.configs.stylistic,
  {
    ignores: ["dist/"],
  },
  {
    linterOptions: {
      noInlineConfig: true,
    },
  },
  {
    rules: {
      // Disable base rules superseded by TypeScript
      "no-unused-vars": "off",
      "no-undef": "off",

      // Complexity limits
      "complexity": "error",
      "max-depth": "error",
      "max-lines": "error",
      "max-lines-per-function": "error",
      "max-nested-callbacks": "error",
      "max-params": "error",
      "max-statements": "error",

      // Code quality rules
      "array-callback-return": "error",
      "block-scoped-var": "error",
      "consistent-return": "error",
      "curly": "error",
      "default-case": "error",
      "default-case-last": "error",
      "dot-notation": "error",
      "eqeqeq": "error",
      "guard-for-in": "error",
      "max-classes-per-file": "error",
      "no-alert": "error",
      "no-caller": "error",
      "no-console": "error",
      "no-constructor-return": "error",
      "no-duplicate-imports": "error",
      "no-else-return": "error",
      "no-empty-function": "error",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-floating-decimal": "error",
      "no-implicit-coercion": "error",
      "no-implied-eval": "error",
      "no-invalid-this": "error",
      "no-iterator": "error",
      "no-lone-blocks": "error",
      "no-loop-func": "error",
      "no-magic-numbers": ["error", { ignore: [-1, 0, 1, 2] }],
      "no-multi-assign": "error",
      "no-multi-str": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-octal-escape": "error",
      "no-param-reassign": "error",
      "no-proto": "error",
      "no-return-assign": "error",
      "no-script-url": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-throw-literal": "error",
      "no-unmodified-loop-condition": "error",
      "no-unused-expressions": "error",
      "no-useless-call": "error",
      "no-useless-concat": "error",
      "no-useless-return": "error",
      "no-void": "error",
      "no-warning-comments": "error",
      "prefer-const": "error",
      "prefer-promise-reject-errors": "error",
      "radix": "error",
      "require-await": "error",
      "vars-on-top": "error",
      "yoda": "error",
    },
  },
  {
    files: ["test/**/*.test.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "no-magic-numbers": "off",
      "complexity": ["error", 200],
      "max-depth": ["error", 40],
      "max-lines": ["error", 3000],
      "max-lines-per-function": ["error", 500],
      "max-nested-callbacks": ["error", 100],
      "max-params": ["error", 30],
      "max-statements": ["error", 100],
    },
  },
);
