const SECONDS_PER_MINUTE = 60;
const MINUTES_PER_HOUR = 60;
const MS_PER_SECOND = 1000;
const HOURS_PER_DAY = 24;

export const MS_PER_HOUR = MINUTES_PER_HOUR * SECONDS_PER_MINUTE * MS_PER_SECOND;
export const MS_PER_DAY = HOURS_PER_DAY * MS_PER_HOUR;
